# Site settings
title: "my very own url shortener"
description: "hopto"

author: Matthew Andres Moreno
author_url: https://mmore500.com/
github_username: mmore500

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:slug

sass:
    style: compressed

exclude: [vendor]

plugins_dir:
  - jekyll-redirect-from
